export const TODO = {
    SET_TASK: "SET-TASK",
    GET_TASKS: "GET-TASKS",
    UPDATE_STATUS: "UPDATE-STATUS",
    DELETE_TASK: "DELETE-TASK",
    REJECTED: "REJECTED",
    CREATED: "CREATED",
    FETCHING: "FETCHING",
    UPDATE_TITLE: "UPDATE-TITLE"
}